### ISSUE TITLE
OI daily SST files changing paths

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadfiles#21]
OI daily SST files updating now, the path has changed.
Previous version (v2) was under the path `/www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/access/avhrr-only/`

That is moving to `/www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2/access/avhrr-only/` BUT only goes to Apr 2020.

Superseded by v2.1 which is under the path `/www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/`

This line needs changing, maybe others too:
https://github.com/AustralianAntarcticDivision/raadfiles/blob/master/R/raad-sst-files.R#L29

**Comment by mdsumner** [comment]
ta, fixed now and raadtools depends on updated raadfiles
