### ISSUE TITLE
`get_raad_data_roots()` can return ""

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadfiles#23]
`get_raad_data_roots()` can return `""` on a machine that doesn't find a valid raad library, but I think most downstream code is looking for `NULL` in this case. I have added one catch (https://github.com/AustralianAntarcticDivision/raadfiles/commit/0f3955a565652524148a10c920c69eb1601d5b6a) but it might be better to explicitly return `NULL` instead of `""`. But I didn't want to do that myself, not knowing what else it might break ...

**Comment by mdsumner** [comment]
I thought I'd improved ... in branch 'wat', but check fails a test and I can't see why ...

**Comment by mdsumner** [comment]
master also failing, so I'll merge and forget the wat branch

**Comment by mdsumner** [comment]
fixed that issue 8a90217 https://twitter.com/mdsumner/status/1415645047379283977?s=20 

`get_raad_data_roots()` should now only return valid strings or NULL
