### ISSUE TITLE
getting files is too slow

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadfiles#28]
If we dump the file list it's 4 seconds to get IBCSO from duckdb, and almost two minutes with raadtools. Something is off, but this might be worth moving to duck anyway. 

```R
library(DBI)
con = dbConnect(duckdb::duckdb(), dbdir="my-db.duckdb", read_only=FALSE)
library(raadfiles)
files <- get_raad_filenames()
dbWriteTable(con, "raadfiles", files)


system.time({
library(tidyverse)
library(DBI)
con = dbConnect(duckdb::duckdb(), dbdir="my-db.duckdb", read_only=TRUE)
tbl(con, "raadfiles") |> filter(str_detect(file, "IBCSO_v2_ice-surface"))
})


system.time({
  library(raadtools)
  topofile("ibcso")
  
})  ## 109.563

```

compare without library attach

```R
library(tidyverse)
library(DBI)
library(raadtools)

system.time({
con = dbConnect(duckdb::duckdb(), dbdir="my-db.duckdb", read_only=TRUE)
tbl(con, "raadfiles") |> filter(str_detect(file, "IBCSO_v2_ice-surface"))
})
#   user  system elapsed 
 # 0.361   0.154   0.368 


system.time({
  topofile("ibcso")
})

```

**Comment by mdsumner** [comment]
this is entirely down to the string searching

```
".*download.pangaea.de/dataset/937574/files/IBCSO_v2_ice-surface.tif$"
```
from the entire archive is slow, but successively with 

```
c("download.pangaea.de/dataset/937574/files/.*", ".*IBCSO_v2_ice-surface.tif$")
```

is so much faster - I guess it has less text to scan without the extra .* at the front? 

Fixed by making topo_file_generic able to loop over multiple patterns.

**Comment by raymondben** [comment]
what about `"download.pangaea.de/dataset/937574/files/IBCSO_v2_ice-surface.tif$"` (no leading `.*` - it should achieve the same as the original)

**Comment by mdsumner** [comment]
probably, I think this just a weird case that I copied out for almost all the sources 🤪

**Comment by mdsumner** [comment]
I'll follow up by putting some checks on all the funs, and hopefully consolidate better as config rather than data in code 👌

**Comment by mdsumner** [comment]
it is entirely about that leading ".*" ... :)   the crux is

```R
## fast
raadfiles:::topo_files_generic("download.pangaea.de/dataset/937574/files/IBCSO_v2_ice-surface.tif$")
## slow
raadfiles:::topo_files_generic("download.pangaea.de/dataset/937574/files/IBCSO_v2_ice-surface.tif$")
```

I'll reboot a bunch of stuff with this in mind
