### ISSUE TITLE
oisst - ensure preliminary files are properly included

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadfiles#5]
Ensure that preliminary files are included if present but correctly overridden by the validate ones if present. 

https://github.com/AustralianAntarcticDivision/blueant/issues/4

**Comment by mdsumner** [comment]
I've create a blueant issue and modified this issue to match.  fyi @raymondben

**Comment by raymondben** [comment]
As far as the prelim downloading, think that is OK now (ref blueant issue closed). As for choosing between prelim/validated files when reading, that's in raadfiles territory.

**Comment by mdsumner** [comment]
all good now!

```R
basename(tail(sstfiles()$fullname))
[1] "avhrr-only-v2.20180215_preliminary.nc" "avhrr-only-v2.20180216_preliminary.nc" "avhrr-only-v2.20180217_preliminary.nc"
[4] "avhrr-only-v2.20180218_preliminary.nc" "avhrr-only-v2.20180219_preliminary.nc" "avhrr-only-v2.20180220_preliminary.nc"
```
