### ISSUE TITLE
triggers on filename invalidation

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadfiles#8]
Currently the file cache is set as a global option and never refreshes until package is reloaded. 

It should refresh on these actions: 

- [ ] the file cache is built (because `set_raadfile_data_roots` is run
- [ ] a time out, can we trigger this from the *files functions, or set an option that gets checked now and then?

**Comment by raymondben** [comment]
On linux, at least, it should be possible to watch the data dir for changes and trigger actions using `inotifywait`. I don't know what the windows/osx equivalents are tho.

**Comment by raymondben** [comment]
```
data_dir <- "/tmp"
library(qtbase)
fsw <- Qt$QFileSystemWatcher()
fsw$addPath(data_dir)
id <- qconnect(fsw, "directoryChanged", function(path) { do_something() })
```
Don't think it works recursively, so may need to add many paths to it, `fsw$addPaths()`
https://doc.qt.io/qt-5/qfilesystemwatcher.html

**Comment by mdsumner** [comment]
`set_raad_filenames` now optionally (`clobber = FALSE`) checks the md5 sums of the file cache sources and is used by the routine `run_this_function_to_build_raad_cache()` - for use by admins in cron jobs and testing. 

With clobber, it rescans the file caches and uploads no matter if there's no change: 
```R
set_raad_filenames(clobber = TRUE)
Uploading raad file cache as at 2018-09-19 11:48:11 (814288 files listed) 


   user  system elapsed 
  1.996   0.040   2.067 
```

Without clobber it checks and does nothing if no change

```R
set_raad_filenames(clobber = F)
Raad file cache is up to date as at 2018-09-19 11:48:11 (814288 files listed) 

  user  system elapsed 
  0.012   0.000   0.014 
```

So, in raadtools any time the file cache is gotten the it can run `set_raad_filenames(clobber = FALSE)` and it should be no more than a couple of seconds. 


 `run_this_function_to_build_raad_cache()`  takes ~320 seconds

**Comment by mdsumner** [comment]
So I think for a user session:

- randomly trigger a reload with a lowish probability, any raadfiles function can do that

**Comment by mdsumner** [comment]
Applied in admin-mode branch

**Comment by mdsumner** [comment]
Pulled into master
